// Let’s practice using the break command to interrupt the loop. Copy the following array (also generated by ChatGPT) to your PHP code:

$fruits = array("Apple", "Banana", "Poisonous Berry", "Strawberry", "Grapes");

Then write the code to print the fruits in the following manner. BUT if the program finds “Poisonous Berry” in the array slot it’s supposed to print, it prints “Hold on a minute! (fruit name) is dangerous!” instead and ends (breaks) the loop.

Today we will eat…
Apple…
Banana…
Hold on a minute! Poisonous Berry is dangerous!

For a bit of extra challenge, you can use the condition that if the fruit name contains the word “poisonous”, it’s considered dangerous and ends the loop.



<?php
$fruits = array("Apple", "Banana", "Poisonous Berry", "Strawberry", "Grapes");
print "Today we will eat ...\n";

foreach ($fruits as $fruit) {
    if (stripos($fruit, "poisonous") !== false) {
        print "Hold on a minute! $fruit is dangerous!\n";
        break;
    } else {
        print "$fruit...\n";
    }
}